if: branch !~ ^v\d
language: node_js
node_js: node
jobs:
  include:
  - dist: xenial
  - os: windows
    env: npm_version=6.9.0 another_npm_version=6.9.1-next.0
    # https://github.com/jasongin/nvs/blob/v1.5.2/test/cli/gitBashTests.js#L36-L39
    before_install: cmd "/C npm install --global npm@${npm_version}"
    before_script: npm --version
    script:
    - npm run-script test-npm-run --silent
    - npx c8 node tests\\no-npm.js
    - npm config set prefix --global tmp
    - npm config get prefix --global
    - cmd "/C npm install --global npm@${another_npm_version}"
    - npx c8 node tests\\win-has-user-npm.js
    - npx c8 node tests\\win-has-broken-user-npm.js
    - npm config set prefix --global foobarbazqux
    - npm config get prefix --global
    - npx c8 node tests\\win-preinstalled-npm.js
    - npx c8 report --reporter=text
after_success: npx c8 report --reporter=lcov && bash <(curl -s https://codecov.io/bash) -X coveragepy -X fix -X gcov -X gcovout -X search -X xcode -f coverage/lcov.info
