image: Visual Studio 2017
platform: x64
shallow_clone: true
skip_tags: true
environment:
  matrix:
    -
      nodejs_version: Stable
      npm_version: '6.3.0'
      another_npm_version: '6.2.0'
      COVERALLS_REPO_TOKEN:
        secure: sL6Zzmwo7A1Hw7dniqi9n+AdBcx59/7h0LBIt9VlebEPqTq0WtSRrLgEw443w33j
      COVERALLS_SERVICE_NAME: AppVeyor
      COVERALLS_SERVICE_JOB_ID: '%APPVEYOR_JOB_ID%'
      COVERALLS_GIT_BRANCH: '%APPVEYOR_REPO_BRANCH%'
      COVERALLS_GIT_COMMIT: '%APPVEYOR_REPO_COMMIT%'
    -
      nodejs_version: LTS
      npm_version: '5.10.0'
      another_npm_version: '5.10.0-next.1'
install:
  - ps: Install-Product node $env:nodejs_version x64
  - 'npm --version # Original npm version'
  - npm install --global npm@%npm_version%
  - set PATH=%APPDATA%\npm;%PATH%
  - 'npm --version # User-installed npm version'
  - npm ci
matrix:
  fast_finish: true
build: off
test_script:
  - npm run-script test-npm-run --silent
  - npx nyc node tests\posix.js
  - npx nyc node tests\no-npm.js
  - npm config set prefix --global tmp
  - npm config get prefix --global
  - npm install --global npm@%another_npm_version%
  - npx nyc node tests\win-has-user-npm.js
  - npx nyc node tests\win-has-broken-user-npm.js
  - npm config set prefix --global foobarbazqux
  - npm config get prefix --global
  - npx nyc node tests\win-preinstalled-npm.js
on_success:
  - npx nyc report --reporter=text
  - ps: If ($env:COVERALLS_REPO_TOKEN) {npx nyc report --reporter=text-lcov | npx --quiet coveralls}
